###Get All Items
GET http://localhost:5000/items HTTP/1.1

###Get Single Item
GET http://localhost:5000/items/63e4ead26bc8a5145e480bd3 HTTP/1.1

###Get Total price
GET http://localhost:5000/items/total HTTP/1.1

###Post Single Item
POST http://localhost:5000/items HTTP/1.1
Content-Type: application/json

{
    "name": "HP",
    "price": 40000
}

###Delete Single Item
DELETE http://localhost:5000/items/63e4eff543dcef095508b658 HTTP/1.1


###Update Single Item
PUT http://localhost:5000/items/6e5281df14cd57484ecc090 HTTP/1.1
Content-Type: application/json

{
    "name": "Elemento",
    "price": 4000
}



###Post Single Product
POST http://localhost:5000/products HTTP/1.1
Content-Type: application/json

{
    "name": "Belmonte",
    "item": "63ea637aed057dc831f53d48"
}

###Get All Products
GET http://localhost:5000/products HTTP/1.1